import { Constants } from "@croquet/croquet";

export function CharacterName(n) {
    return Constants.Characters[n].name;
}

export function CharacterFlavor(n) {
    return Constants.Characters[n].flavor;
}

export function CharacterCount() {
    return Constants.Characters.length;
}

Constants.Characters = [
{name: "A Balrog of Morgoth", flavor: ""},
{name: "A Bucket of Water", flavor: ""},
{name: "A Dalek", flavor: ""},
{name: "A Dementor", flavor: ""},
{name: "A Horrible Goose", flavor: ""},
{name: "A Minion", flavor: ""},
{name: "A Munchkin", flavor: ""},
{name: "A Roomba with a Knife", flavor: ""},
{name: "A Stormtrooper", flavor: ""},
{name: "A Trained Chimp", flavor: ""},
{name: "Aeon Flux", flavor: ""},
{name: "Agent Coulson", flavor: ""},
{name: "Agent Smith", flavor: ""},
{name: "Aladdin", flavor: ""},
{name: "Albus Dumbledore", flavor: ""},
{name: "ALF", flavor: ""},
{name: "Alvin the Chipmunk", flavor: ""},
{name: "An Oompa Loompa", flavor: ""},
{name: "Angelica Pickles", flavor: ""},
{name: "Anton Chigurh", flavor: ""},
{name: "Aquaman", flavor: ""},
{name: "Ariel", flavor: ""},
{name: "Aslan", flavor: ""},
{name: "Astroboy", flavor: ""},
{name: "Audrey II", flavor: ""},
{name: "Augustus Gloop", flavor: ""},
{name: "Auric Goldfinger", flavor: ""},
{name: "Austin Powers", flavor: ""},
{name: "Babar", flavor: ""},
{name: "Baby Yoda", flavor: ""},
{name: "Bambi", flavor: ""},
{name: "Barbie", flavor: ""},
{name: "Barney the Dinosaur", flavor: ""},
{name: "Baron Munchausen", flavor: ""},
{name: "Bart Simpson", flavor: ""},
{name: "Batman", flavor: ""},
{name: "Beetlejuice", flavor: ""},
{name: "Bellatrix Lestrange", flavor: ""},
{name: "Bender", flavor: ""},
{name: "Benjamin Button", flavor: ""},
{name: "Betty Boop", flavor: ""},
{name: "Big Bird", flavor: ""},
{name: "Bigfoot", flavor: ""},
{name: "Bilbo Baggins", flavor: ""},
{name: "Bill Cypher", flavor: ""},
{name: "Bill the Pony", flavor: ""},
{name: "Bing Bong", flavor: ""},
{name: "Bizarro Superman", flavor: ""},
{name: "Black Panther", flavor: ""},
{name: "Black Widow", flavor: ""},
{name: "Blade", flavor: ""},
{name: "Bluto", flavor: ""},
{name: "Bob the Builder", flavor: ""},
{name: "Boba Fett", flavor: ""},
{name: "Bojack Horseman", flavor: ""},
{name: "Boomhauer", flavor: ""},
{name: "Boromir", flavor: ""},
{name: "Boss Baby", flavor: ""},
{name: "Brainy Smurf", flavor: ""},
{name: "Brock Sampson", flavor: ""},
{name: "Buckaroo Banzai", flavor: ""},
{name: "Buffy the Vampire Slayer", flavor: ""},
{name: "Bugs Bunny", flavor: ""},
{name: "Bumblebee", flavor: ""},
{name: "Buzz Lightyear", flavor: ""},
{name: "C-3PO", flavor: ""},
{name: "Caillou", flavor: ""},
{name: "Cap'n Crunch", flavor: ""},
{name: "Captain America", flavor: ""},
{name: "Captain Haddock", flavor: ""},
{name: "Captain Harlock", flavor: ""},
{name: "Captain Hook", flavor: ""},
{name: "Captain Jack Sparrow", flavor: ""},
{name: "Captain Marvel", flavor: ""},
{name: "Captain Nemo", flavor: ""},
{name: "Captain Planet", flavor: ""},
{name: "Captain Underpants", flavor: ""},
{name: "Carmen Sandiego", flavor: ""},
{name: "Cartman", flavor: ""},
{name: "Caspar the Friendly Ghost", flavor: ""},
{name: "Catbus", flavor: ""},
{name: "Catra", flavor: ""},
{name: "Catwoman", flavor: ""},
{name: "Chargeman Ken", flavor: ""},
{name: "Charizard", flavor: ""},
{name: "Charlie Brown", flavor: ""},
{name: "Chucky", flavor: ""},
{name: "Clifford the Big Red Dog", flavor: ""},
{name: "Clippy", flavor: ""},
{name: "Cobra Commander", flavor: ""},
{name: "Conan the Barbarian", flavor: ""},
{name: "Cookie Monster", flavor: ""},
{name: "Coraline", flavor: ""},
{name: "Count Chocula", flavor: ""},
{name: "Count Dracula", flavor: ""},
{name: "Count Olaf", flavor: ""},
{name: "Count von Count", flavor: ""},
{name: "Cruella De Vil", flavor: ""},
{name: "Cthulhu", flavor: ""},
{name: "Curious George", flavor: ""},
{name: "Daddy Warbucks", flavor: ""},
{name: "Daenerys Targaryen", flavor: ""},
{name: "Daffy Duck", flavor: ""},
{name: "Damien", flavor: ""},
{name: "Daphne", flavor: ""},
{name: "Daria", flavor: ""},
{name: "Darth Vader", flavor: ""},
{name: "Data", flavor: ""},
{name: "Data's Cat", flavor: ""},
{name: "Davy Jones", flavor: ""},
{name: "Deadpool", flavor: ""},
{name: "Dick Tracy", flavor: ""},
// {name: "Dirty Harry", flavor: ""},
{name: "Doc Brown", flavor: ""},
{name: "Doc Ock", flavor: ""},
{name: "Doctor Doom", flavor: ""},
{name: "Doctor Evil", flavor: ""},
{name: "Doctor Girlfriend", flavor: ""},
{name: "Doctor Manhattan", flavor: ""},
{name: "Doctor Strange", flavor: ""},
{name: "Doctor Zeus", flavor: ""},
{name: "Dolores Umbridge", flavor: ""},
{name: "Donald Duck", flavor: ""},
{name: "Donkey Kong", flavor: ""},
{name: "Dora the Explorer", flavor: ""},
{name: "Dorothy", flavor: ""},
{name: "Dr. Dolittle", flavor: ""},
{name: "Dr. Doofenshmirtz", flavor: ""},
{name: "Dr. Frank-n-furter", flavor: ""},
{name: "Dr. Strangelove", flavor: ""},
{name: "Dr. Zoidberg", flavor: ""},
{name: "Dumbo", flavor: ""},
{name: "E.T.", flavor: ""},
{name: "Ebenezer Scrooge", flavor: ""},
{name: "Edna Mode", flavor: ""},
{name: "Edward Scissorhands", flavor: ""},
{name: "Eeyore", flavor: ""},
{name: "Ellen Ripley", flavor: ""},
{name: "Elmer Fudd", flavor: ""},
{name: "Elmo", flavor: ""},
{name: "Elsa", flavor: ""},
{name: "Emperor Kuzco", flavor: ""},
{name: "Emperor Palpatine", flavor: ""},
{name: "Entrapta", flavor: ""},
{name: "Éowyn", flavor: ""},
{name: "Falkor", flavor: ""},
{name: "Ferris Bueller", flavor: ""},
{name: "Fezzik", flavor: ""},
{name: "Fievel", flavor: ""},
{name: "Flash Gordon", flavor: ""},
{name: "Flipper", flavor: ""},
{name: "Forrest Gump", flavor: ""},
{name: "Frankenstein", flavor: ""},
{name: "Fred", flavor: ""},
{name: "Fred Flintstone", flavor: ""},
{name: "Fred Fredburger", flavor: ""},
{name: "Freddie Kruger", flavor: ""},
{name: "Fredo Corleone", flavor: ""},
{name: "Frodo Baggins", flavor: ""},
{name: "Frosty the Snowman", flavor: ""},
{name: "Frozone", flavor: ""},
{name: "Galadriel", flavor: ""},
{name: "Gamera", flavor: ""},
{name: "Gandalf the Grey", flavor: ""},
{name: "Garfield", flavor: ""},
{name: "Garth Marenghi", flavor: ""},
{name: "Gaston", flavor: ""},
{name: "Geordi La Forge", flavor: ""},
{name: "Geppetto", flavor: ""},
{name: "Gimli", flavor: ""},
{name: "Gir", flavor: ""},
{name: "GLaDOS", flavor: ""},
{name: "Glenda the Good Witch", flavor: ""},
{name: "Godzilla", flavor: ""},
{name: "Goku", flavor: ""},
{name: "Gollum", flavor: ""},
{name: "Gomez Addams", flavor: ""},
{name: "Goofy", flavor: ""},
{name: "Gorilla Grod", flavor: ""},
{name: "Green Arrow", flavor: ""},
{name: "Green Lantern", flavor: ""},
{name: "Gregor Samsa\n(cockroach form)", flavor: ""},
{name: "Gritty", flavor: ""},
{name: "Groot", flavor: ""},
{name: "Hades", flavor: ""},
{name: "Hagrid", flavor: ""},
{name: "HAL-9000", flavor: ""},
{name: "Han Solo", flavor: ""},
{name: "Hank Hill", flavor: ""},
{name: "Hannibal Lecter", flavor: ""},
{name: "Harley Quinn", flavor: ""},
{name: "Harry Potter", flavor: ""},
{name: "Hatsune Miku", flavor: ""},
{name: "He-Man", flavor: ""},
{name: "Hellboy", flavor: ""},
{name: "Hello Kitty", flavor: ""},
{name: "Herbie the Love Bug", flavor: ""},
{name: "Hercules", flavor: ""},
{name: "Hermione Granger", flavor: ""},
{name: "Homer Simpson", flavor: ""},
{name: "Howard the Duck", flavor: ""},
{name: "Imperator Furiosa", flavor: ""},
{name: "Indiana Jones", flavor: ""},
{name: "Inigo Montoya", flavor: ""},
{name: "Inspector Clouseau", flavor: ""},
{name: "Inspector Columbo", flavor: ""},
{name: "Inspector Gadget", flavor: ""},
{name: "Invader Zim", flavor: ""},
{name: "Iron Man", flavor: ""},
{name: "Jabba the Hutt", flavor: ""},
{name: "Jack Frost", flavor: ""},
{name: "Jack Skellington", flavor: ""},
{name: "Jack Torrance", flavor: ""},
{name: "Jafar", flavor: ""},
{name: "James Bond", flavor: ""},
{name: "James T. Kirk", flavor: ""},
{name: "Jar Jar Binks", flavor: ""},
{name: "Jareth, the Goblin King", flavor: ""},
{name: "Jason Voorhees", flavor: ""},
{name: "Jean-Luc Picard", flavor: ""},
{name: "Jessica Rabbit", flavor: ""},
{name: "Jiminy Cricket", flavor: ""},
{name: "Jimmy Neutron", flavor: ""},
{name: "John McClane", flavor: ""},
{name: "John Shaft", flavor: ""},
{name: "John Wick", flavor: ""},
{name: "Jonny Quest", flavor: ""},
{name: "Judge Dredd", flavor: ""},
{name: "Judy Hopps", flavor: ""},
{name: "Jughead", flavor: ""},
{name: "Jules Winnfield", flavor: ""},
{name: "Katniss Everdeen", flavor: ""},
{name: "Kenny", flavor: ""},
{name: "Kermit the Frog", flavor: ""},
{name: "Keyser Söze", flavor: ""},
{name: "Khan Noonien Singh", flavor: ""},
{name: "Kim Possible", flavor: ""},
{name: "King Kong", flavor: ""},
{name: "Kirby", flavor: ""},
{name: "Kratos", flavor: ""},
{name: "Krazy Kat", flavor: ""},
{name: "Kronk", flavor: ""},
{name: "Krusty the Clown", flavor: ""},
{name: "Krypto the Superdog", flavor: ""},
{name: "Kylo Renn", flavor: ""},
{name: "Lando Calrissian", flavor: ""},
{name: "Lara Croft", flavor: ""},
{name: "Lassie", flavor: ""},
{name: "Leela", flavor: ""},
{name: "Legolas", flavor: ""},
{name: "Leslie Knope", flavor: ""},
{name: "Lex Luthor", flavor: ""},
{name: "Lightning McQueen", flavor: ""},
{name: "Link", flavor: ""},
{name: "Lisa Simpson", flavor: ""},
{name: "Little Orphan Annie", flavor: ""},
{name: "Little Red Riding Hood", flavor: ""},
{name: "Liz Lemon", flavor: ""},
{name: "Lois Lane", flavor: ""},
{name: "Loki", flavor: ""},
{name: "Lola Bunny", flavor: ""},
{name: "Long John Silver", flavor: ""},
{name: "Lord Voldemort", flavor: ""},
{name: "Lore", flavor: ""},
{name: "Louise Belcher", flavor: ""},
{name: "Lowly Worm", flavor: ""},
{name: "Lucy Ricardo", flavor: ""},
{name: "Luigi", flavor: ""},
{name: "Luke Skywalker", flavor: ""},
{name: "Luna Lovegood", flavor: ""},
{name: "Lupin III", flavor: ""},
{name: "Lurch", flavor: ""},
{name: "Lydia Deetz", flavor: ""},
{name: "Macavity", flavor: ""},
{name: "MacGyver", flavor: ""},
{name: "Mad Max", flavor: ""},
{name: "Madea", flavor: ""},
{name: "Madeline", flavor: ""},
{name: "Magneto", flavor: ""},
{name: "Major Kusunagi", flavor: ""},
{name: "Maleficient ", flavor: ""},
{name: "Mario", flavor: ""},
{name: "Marion Ravenwood", flavor: ""},
{name: "Marty Mcfly", flavor: ""},
{name: "Mary Poppins", flavor: ""},
{name: "Master Chief", flavor: ""},
{name: "Matter-Eater Lad", flavor: ""},
{name: "Max Headroom", flavor: ""},
{name: "McGruff the Crime Dog", flavor: ""},
{name: "Megamind", flavor: ""},
{name: "Megatron", flavor: ""},
{name: "Meowth", flavor: ""},
{name: "Merlin", flavor: ""},
{name: "Metapod", flavor: ""},
{name: "Michael Corleone", flavor: ""},
{name: "Mickey Mouse", flavor: ""},
{name: "Mighty Mouse", flavor: ""},
{name: "Minerva McGonagall", flavor: ""},
{name: "Mini-me", flavor: ""},
{name: "Mirror Universe Spock", flavor: ""},
{name: "Miss Piggy", flavor: ""},
{name: "Mojo Jojo", flavor: ""},
{name: "Monkey D. Luffy", flavor: ""},
{name: "Moomintroll", flavor: ""},
{name: "Morgan le Fay", flavor: ""},
{name: "Morpheus", flavor: ""},
{name: "Morticia Addams", flavor: ""},
{name: "Morty Smith", flavor: ""},
{name: "Mr. Bean", flavor: ""},
{name: "Mr. Burns", flavor: ""},
{name: "Mr. Clean", flavor: ""},
{name: "Mr. Creosote", flavor: ""},
{name: "Mr. Ed", flavor: ""},
{name: "Mr. Fantastic", flavor: ""},
{name: "Mr. Freeze", flavor: ""},
{name: "Mr. Krabs", flavor: ""},
{name: "Mr. Magoo", flavor: ""},
{name: "Mr. Miyagi", flavor: ""},
{name: "Mr. Mxyzptlk", flavor: ""},
{name: "Mr. Peabody", flavor: ""},
{name: "Mr. Peanut", flavor: ""},
{name: "Mr. Snuffleupagus", flavor: ""},
{name: "Mr. Toad", flavor: ""},
{name: "Mr. Tumnus", flavor: ""},
{name: "Mrs. Potts", flavor: ""},
{name: "Ms. Frizzle", flavor: ""},
{name: "Mulan", flavor: ""},
{name: "Mystique", flavor: ""},
{name: "Nancy", flavor: ""},
{name: "Napoleon Dynamite", flavor: ""},
{name: "Naruto", flavor: ""},
{name: "Ned Flanders", flavor: ""},
{name: "Neo", flavor: ""},
{name: "Neville Longbottom", flavor: ""},
{name: "Nick Fury", flavor: ""},
{name: "Nigel Thornberry", flavor: ""},
{name: "Norman Bates", flavor: ""},
{name: "Nosferatu", flavor: ""},
// {name: "Nyarlathotep, the Crawling Chaos", flavor: ""},
{name: "Obi-Wan Kenobi", flavor: ""},
{name: "Oddjob", flavor: ""},
{name: "Odie", flavor: ""},
{name: "Olive Oyl", flavor: ""},
{name: "Oogie Boogie", flavor: ""},
{name: "Optimus Prime", flavor: ""},
{name: "Oscar the Grouch", flavor: ""},
{name: "Osmosis Jones", flavor: ""},
{name: "Pac-Man", flavor: ""},
{name: "Paddington Bear", flavor: ""},
{name: "Papa Smurf", flavor: ""},
{name: "Patrick Star", flavor: ""},
{name: "Peewee Herman", flavor: ""},
{name: "Pennywise the Clown", flavor: ""},
{name: "Pepé Le Pew ", flavor: ""},
{name: "Peppa Pig", flavor: ""},
{name: "Perry the Platypus", flavor: ""},
{name: "Peter Griffin", flavor: ""},
{name: "Peter Pan", flavor: ""},
{name: "Philip J. Fry", flavor: ""},
{name: "Phoenix Wright", flavor: ""},
{name: "Piglet", flavor: ""},
{name: "Pikachu", flavor: ""},
{name: "Pinhead", flavor: ""},
{name: "Plankton", flavor: ""},
{name: "Poison Ivy", flavor: ""},
{name: "Ponyo", flavor: ""},
{name: "Popeye", flavor: ""},
{name: "Porky Pig", flavor: ""},
{name: "Princess Bubblegum", flavor: ""},
{name: "Princess Buttercup", flavor: ""},
{name: "Princess Leia", flavor: ""},
{name: "Princess Peach", flavor: ""},
{name: "Princess Unikitty", flavor: ""},
{name: "Princess Zelda", flavor: ""},
{name: "Professor Moriarty", flavor: ""},
{name: "Professor X", flavor: ""},
{name: "Puff the Magic Dragon", flavor: ""},
{name: "Puss-in-Boots", flavor: ""},
{name: "Pyramid Head", flavor: ""},
// {name: "Q", flavor: ""},
{name: "R2-D2", flavor: ""},
{name: "Race Bannon", flavor: ""},
{name: "Rambo", flavor: ""},
{name: "Ranma", flavor: ""},
{name: "Rapunzel", flavor: ""},
{name: "Red Skull", flavor: ""},
{name: "Richie Rich", flavor: ""},
{name: "Rick Sanchez", flavor: ""},
{name: "Robbie Rotten", flavor: ""},
{name: "Robin the Boy Wonder", flavor: ""},
{name: "Robocop", flavor: ""},
{name: "Rocket Raccoon ", flavor: ""},
{name: "Rocky Balboa", flavor: ""},
{name: "Roger Rabbit", flavor: ""},
{name: "Ron Burgundy", flavor: ""},
{name: "Ron Swanson", flavor: ""},
{name: "Ron Weasley", flavor: ""},
{name: "Ronald McDonald", flavor: ""},
{name: "Roy Batty", flavor: ""},
{name: "Rudolph the Red-Nosed Reindeer", flavor: ""},
{name: "Sabrina the Teenage Witch", flavor: ""},
{name: "Sackboy", flavor: ""},
{name: "Sadako", flavor: ""},
{name: "Sailor Moon", flavor: ""},
{name: "Sam the Eagle", flavor: ""},
{name: "Samus Aran", flavor: ""},
{name: "Sandy Cheeks", flavor: ""},
{name: "Santa Claus", flavor: ""},
{name: "Sarah Connor", flavor: ""},
{name: "Saruman the White", flavor: ""},
{name: "Sauron", flavor: ""},
{name: "Scar", flavor: ""},
{name: "Scooby Doo", flavor: ""},
{name: "Scotty", flavor: ""},
{name: "Scrappy Doo", flavor: ""},
{name: "Scrat", flavor: ""},
{name: "Scrooge McDuck", flavor: ""},
{name: "Severus Snape", flavor: ""},
{name: "Seymour Skinner", flavor: ""},
{name: "Shaggy", flavor: ""},
{name: "She-Hulk", flavor: ""},
{name: "She-Ra", flavor: ""},
{name: "Sheldon Cooper", flavor: ""},
{name: "Shelob", flavor: ""},
{name: "Shere Khan", flavor: ""},
{name: "Sherlock Holmes", flavor: ""},
{name: "Shinji Ikari", flavor: ""},
{name: "Shrek", flavor: ""},
{name: "Sir Topham Hatt", flavor: ""},
{name: "Skeletor", flavor: ""},
{name: "Skimbleshanks the Railway Cat", flavor: ""},
{name: "Slenderman", flavor: ""},
{name: "Slimer", flavor: ""},
{name: "Sluggo", flavor: ""},
{name: "Sly Cooper", flavor: ""},
{name: "Smaug", flavor: ""},
{name: "Smurfette", flavor: ""},
{name: "Snake Eyes", flavor: ""},
{name: "Snake Plissken", flavor: ""},
{name: "Snoopy", flavor: ""},
{name: "Snow White", flavor: ""},
{name: "Snufkin", flavor: ""},
{name: "Solid Snake", flavor: ""},
{name: "Sonic the Hedgehog", flavor: ""},
{name: "Special Agent Cooper", flavor: ""},
{name: "Speed Racer", flavor: ""},
{name: "Speedy Gonzales", flavor: ""},
{name: "Spock", flavor: ""},
{name: "Spongebob Squarepants", flavor: ""},
{name: "Sportacus", flavor: ""},
{name: "Spuds MacKenzie", flavor: ""},
{name: "Spyro the Dragon", flavor: ""},
{name: "Squidward Tentacles", flavor: ""},
{name: "Squirrel Girl", flavor: ""},
{name: "Starscream", flavor: ""},
{name: "Sterling Archer", flavor: ""},
{name: "Stewie Griffin", flavor: ""},
{name: "Stitch", flavor: ""},
{name: "Strawberry Shortcake", flavor: ""},
{name: "Strong Bad", flavor: ""},
{name: "Stuart Little", flavor: ""},
{name: "Sulu", flavor: ""},
{name: "Supergirl", flavor: ""},
{name: "Superman", flavor: ""},
{name: "Swiper the Fox", flavor: ""},
{name: "Tank Girl", flavor: ""},
{name: "Tarzan", flavor: ""},
{name: "Thanos", flavor: ""},
{name: "The $6,000,000 Man", flavor: ""},
{name: "The Babadook", flavor: ""},
{name: "The Big Bad Wolf", flavor: ""},
{name: "The Bionic Woman", flavor: ""},
{name: "The Black Knight", flavor: ""},
{name: "The Blob", flavor: ""},
{name: "The Brave Little Toaster", flavor: ""},
{name: "The Bride", flavor: ""},
{name: "The Cat in the Hat", flavor: ""},
{name: "The Cheshire Cat", flavor: ""},
{name: "The Cowardly Lion", flavor: ""},
{name: "The Creature from the Black Lagoon", flavor: ""},
{name: "The Doctor", flavor: ""},
{name: "The Dread Pirate Roberts", flavor: ""},
{name: "The Dude", flavor: ""},
{name: "The Easter Bunny", flavor: ""},
{name: "The Energizer Bunny", flavor: ""},
{name: "The Flash", flavor: ""},
{name: "The Fonz", flavor: ""},
{name: "The GEICO Gecko", flavor: ""},
{name: "The Genie", flavor: ""},
{name: "The Ghost of Christmas Future", flavor: ""},
{name: "The Ghost of Christmas Past", flavor: ""},
{name: "The Ghost of Christmas Present", flavor: ""},
{name: "The Giving Tree", flavor: ""},
{name: "The Grim Reaper", flavor: ""},
{name: "The Grinch", flavor: ""},
{name: "The Human Torch", flavor: ""},
{name: "The Incredible Hulk", flavor: ""},
{name: "The Invisible Girl", flavor: ""},
{name: "The Invisible Man", flavor: ""},
{name: "The Iron Giant", flavor: ""},
{name: "The Jabberwock", flavor: ""},
{name: "The Joker", flavor: ""},
{name: "The Jolly Green Giant", flavor: ""},
{name: "The Kool-Aid Man", flavor: ""},
{name: "The Kraken", flavor: ""},
{name: "The Little Engine that Could", flavor: ""},
{name: "The Little Prince", flavor: ""},
{name: "The Loch Ness Monster", flavor: ""},
{name: "The Lone Ranger", flavor: ""},
{name: "The Lorax", flavor: ""},
{name: "The Mad Hatter", flavor: ""},
{name: "The Magical Mr. Mistoffelees", flavor: ""},
{name: "The Man in the Yellow Hat", flavor: ""},
{name: "The Man with No Name", flavor: ""},
// {name: "The Man with Thistledown Hair", flavor: ""},
{name: "The Master", flavor: ""},
{name: "The Michelin Man", flavor: ""},
{name: "The Most Interesting Man in the World", flavor: ""},
{name: "The Mummy", flavor: ""},
{name: "The Once-ler", flavor: ""},
{name: "The Other Mother", flavor: ""},
{name: "The Penguin", flavor: ""},
{name: "The Phantom of the Opera", flavor: ""},
{name: "The Pillsbury Dough Boy", flavor: ""},
{name: "The Pink Panther", flavor: ""},
{name: "The Predator", flavor: ""},
{name: "The Roadrunner", flavor: ""},
{name: "The Sarlacc", flavor: ""},
{name: "The Scarecrow", flavor: ""},
{name: "The Stay-Puft Marshmallow Man", flavor: ""},
{name: "The Swedish Chef", flavor: ""},
{name: "The Tasmanian Devil", flavor: ""},
{name: "The Terminator", flavor: ""},
{name: "The Thing", flavor: ""},
{name: "The Tin Man", flavor: ""},
{name: "The Tooth Fairy", flavor: ""},
{name: "The Velveteen Rabbit", flavor: ""},
{name: "The Very Hungry Caterpillar", flavor: ""},
{name: "The White Witch", flavor: ""},
{name: "The Wicked Witch of the West", flavor: ""},
{name: "The Witch King", flavor: ""},
{name: "The Wizard of Oz", flavor: ""},
{name: "The Wonder Twins", flavor: ""},
{name: "The Xenomorph (Alien)", flavor: ""},
{name: "Thomas the Tank Engine", flavor: ""},
{name: "Thor", flavor: ""},
{name: "Tigger", flavor: ""},
{name: "Tim the Enchanter", flavor: ""},
{name: "Timmy Turner", flavor: ""},
{name: "Tina Belcher", flavor: ""},
{name: "Tinker Bell", flavor: ""},
{name: "Tintin", flavor: ""},
{name: "Tiny Tim", flavor: ""},
{name: "Tom Bombadil", flavor: ""},
{name: "Tom Nook", flavor: ""},
{name: "Tom Servo", flavor: ""},
{name: "Tonto", flavor: ""},
{name: "Tony Montana (Scarface)", flavor: ""},
{name: "Tony Soprano", flavor: ""},
{name: "Tony the Tiger", flavor: ""},
{name: "Toto (too)", flavor: ""},
{name: "Totoro", flavor: ""},
{name: "Toucan Sam", flavor: ""},
{name: "Travis Bickle", flavor: ""},
{name: "Treebeard", flavor: ""},
{name: "Trevor Goodchild", flavor: ""},
{name: "Trinity", flavor: ""},
{name: "Trogdor the Burninator", flavor: ""},
{name: "Tuxedo Mask", flavor: ""},
{name: "Tweety Bird", flavor: ""},
{name: "Twilight Sparkle", flavor: ""},
{name: "Tyler Durden", flavor: ""},
{name: "Tyrion Lannister ", flavor: ""},
{name: "Uhura", flavor: ""},
{name: "Uncle Fester", flavor: ""},
{name: "Vanellope von Schweetz", flavor: ""},
{name: "Vegeta", flavor: ""},
{name: "Velma", flavor: ""},
{name: "Veruca Salt", flavor: ""},
{name: "Vincent Vega", flavor: ""},
{name: "Violet Beauregarde", flavor: ""},
{name: "Vito Corleone", flavor: ""},
{name: "Vizzini", flavor: ""},
// {name: "Voltron", flavor: ""},
{name: "WALL-E", flavor: ""},
{name: "Walter White", flavor: ""},
{name: "Waluigi", flavor: ""},
{name: "Wario", flavor: ""},
{name: "Wednesday Addams", flavor: ""},
{name: "Wesley Crusher", flavor: ""},
{name: "Wile E. Coyote", flavor: ""},
{name: "Willy Wonka", flavor: ""},
{name: "Wilson", flavor: ""},
{name: "Winnie-the-Pooh", flavor: ""},
{name: "Wishbone", flavor: ""},
{name: "Wolverine", flavor: ""},
{name: "Wonder Woman", flavor: ""},
{name: "Woody", flavor: ""},
{name: "Worf", flavor: ""},
{name: "Wreck-it Ralph", flavor: ""},
{name: "Xena, Warrior Princess", flavor: ""},
{name: "Yoda (non-baby)", flavor: ""},
{name: "Yog Sothoth", flavor: ""},
{name: "Yogi Bear", flavor: ""},
{name: "Yosemite Sam", flavor: ""},
{name: "Yoshi", flavor: ""},
{name: "Yzma", flavor: ""},
{name: "Zaphod Beeblebrox", flavor: ""},
{name: "Zapp Brannigan", flavor: ""},
// {name: "Zoot ... just Zoot", flavor: ""},
{name: "Zorro", flavor: ""},
];
