import { Constants } from "@croquet/croquet";

export function Question(n) {
    return Constants.Questions[n];
}

export function QuestionCount() {
    return Constants.Questions.length;
}

Constants.Questions = [
'Who would win a battle to the death?',
'Who should be king of the world??',
'Who takes the longest to get ready in the morning?',
'Who would win a pie-eating contest?',
'Who would you rather be stranded on a desert island with?',
'Who would you rather be quarantined with?',
'Who would you rob a bank with?',
'Who really needs to be in therapy?',
'Who should be utterly erased from existence?',
'Who would help you hide a body?',
'Who would be the most useful during a zombie apocalyse?',
'Who is the worst at their job?',
'Who has the worst pickup line?',
"Who would you be most surprised to see working at McDonald's?",
'Who has the best fashion sense?',
'Who is the worst tipper?',
'Who would you trust with your darkest secret?',
'Who would you ask to help you move?',
'Who would you send back in time to kill Hitler?',
'Who would you rather take a roadtrip with?',
"Who's the fairest one of all?",
'Who would you rather build an IKEA bookcase with?',
'Who should save little Timmy from the well?',
'Who should watch the baby?',
'Who would make the best cult leader?',
'Who is secretly a sleeper agent?',
'Who would you rather spend a weekend in Vegas with?',
'Who deserves to win the lottery?',
'Who would make the worst middle-school gym teacher?',
'Who would win a freestyle rap battle?',
'Who would never give you up?',
'Who would never let you down?',
'Who would never run around and desert you?',
'Who should cook dinner tonight?',
'Who really knows how to hold a grudge?',
'Who would you rather spend the night with?',
'Who would win a talent show?',
'Who should drive the getaway car?',
'Who would you avoid in Walmart?',
'Who would you crash a wedding with?',
'Who really needs a vacation?',
'Who looks best in drag?',
'Who had the longest emo phase?',
'Who picks up the check?',
'Who da man?',
"Who's missing the big picture?",
'Who would you not get into a hot tub with?',
'Who smells the best?',
'Who smells the worst?',
'Who should ride shotgun?',
'Who would you frame for murder?',
'Who ate the last cookie?',
"Who deserves to be taken down a notch?",
"Who needs hug?",
"Who should be on the cover of the swimsuit issue?",
"Who would you rather go dumpster diving with?",
"Who would be the first one voted off the island?",
"Who would make the worst ex?",
"Who would be most likely to ghost you after one date?",
"Who parties the hardest?",
"Who can't hold their liquor?",
"Who's the most diligent about recycling?",
"Who wants to speak to the manager?",
"Who's the brains of the operation?",
"Who would you NOT want to work for?",
"Who's the cat who won't cop out when there's danger all about?",
"Who secretly suffers from massive self-loathing?",
"Who had the worst childhood?",
"Who would you rather go to Disneyland with?",
"Who would you rather have a romantic dinner with?",
"Who's just the absolute worst?",
"Who really needs a makeover?",
"Who would you like to switch places with for a day?",
"Who is the best kisser?",
"Who is the worst kisser?",
"Who would you trust to disarm a ticking time bomb?",
"Who is a ticking time bomb?",
"Who has the best secret lair?",
"Who should clean the bathroom?",
"Who should star in their own rom-com?",
"Who would you be least surprised to discover was a serial killer?",
"Who has the best hair?",
"Who would make the best roommate?",
"Who always gets picked first for dodgeball?",
"Who always gets picked last for dodgeball?",
"Who should be captain of the cheerleading squad?",
"Who should be homecoming queen?",
"Who has the sickest moves?",
"Who should play bass in the band?",
"Who's the most punk?",
"Who's just phoning it in?",
"Who should host Thanksgiving this year?",
"Who throws the best parties?",
"Who should host the Oscars?",
"Who should have their own late night talk show?",
"Who would you go to for relationship advice?",
"Who's the biggest gossip?",
"Who has the blackest heart?",
"Who's the scariest?",
"Who's really just a big softie?",
"Who's the biggest dumpster fire?",
"Who's the hottest mess?",
"Who's the cutest?",
];
