import { Constants } from "@croquet/worldcore";

export function CharacterName(n) {
    return Constants.Characters[n];
}

export function CharacterCount() {
    return Constants.Characters.length;
}

Constants.Characters = [
    "A Balrog of Morgoth",
    "A Bucket of Water",
    "A Dalek",
    "A Dementor",
    "A Minion",
    "A Roomba with a Knife",
    "A Trained Chimp",
    "Aeon Flux",
    "Aladdin",
    "Albus Dumbledore",
    "Alvin the Chipmunk",
    "An Angry Goose",
    "An Oompa Loompa",
    "Angelica Pickles",
    "Aquaman",
    "Ariel",
    "Aslan the Lion",
    "Augustus Gloop",
    "Goldfinger",
    "Austin Powers",
    "Babar the Elephant",
    "Baby Yoda",
    "Bambi",
    "Barbie",
    "Barney the Dinosaur",
    "Baron Munchausen",
    "Bart Simpson",
    "Batman",
    "Batgirl",
    "Beetlejuice",
    "Bellatrix Lestrange",
    "Betty Boop",
    "Big Bird",
    "Bigfoot",
    "Bilbo Baggins",
    "Bizarro Superman",
    "Black Panther",
    "Black Widow",
    "Bluto",
    "Boba Fett",
    "Bobby Hill",
    "Bojack Horseman",
    "Boomhauer",
    "Boromir",
    "Boss Baby",
    "Brainy Smurf",
    "Brock Sampson",
    "Buffy the Vampire Slayer",
    "Bugs Bunny",
    "Buzz Lightyear",
    "C-3PO",
    "Caillou",
    "Cap'n Crunch",
    "Captain America",
    "Captain Hook",
    "Captain Jack Sparrow",
    "Captain Marvel",
    "Captain Nemo",
    "Captain Planet",
    "Captain Underpants",
    "Carmen Sandiego",
    "Cartman",
    "Caspar the Friendly Ghost",
    "Catbus",
    "Catra",
    "Catwoman",
    "Charlie Brown",
    "Clifford the Big Red Dog",
    "Clippy",
    "Cobra Commander",
    "Conan the Barbarian",
    "Cookie Monster",
    "Coraline",
    "Count Chocula",
    "Count Dracula",
    "Count von Count",
    "Cruella De Vil",
    "Cthulhu",
    "Curious George",
    "Daffy Duck",
    "Daphne",
    "Daria",
    "Darth Vader",
    "Data",
    "Deadpool",
    "Dick Tracy",
    "Doctor Doom",
    "Doctor Girlfriend",
    "Doctor Manhattan",
    "Doctor Strange",
    "Dolores Umbridge",
    "Donald Duck",
    "Donkey Kong",
    "Dora the Explorer",
    "Dorothy",
    "Dr. Doofenshmirtz",
    "Dr. Frank-n-furter",
    "Dr. Zoidberg",
    "Dumbo",
    "E.T.",
    "Ebenezer Scrooge",
    "Eeyore",
    "Elmer Fudd",
    "Elmo",
    "Elsa",
    "Emperor Kuzco",
    "Emperor Palpatine",
    "Éowyn",
    "Ferris Bueller",
    "Fezzik",
    "Frankenstein's monster",
    "Fred Flintstone",
    "Freddie Kruger",
    "Frodo Baggins",
    "Frosty the Snowman",
    "Galadriel",
    "Gandalf the Grey",
    "Garfield",
    "Gaston",
    // "Geordi La Forge",
    "Geppetto",
    "Gimli",
    "Gir",
    "GLaDOS",
    "Glinda the Good Witch",
    "Godzilla",
    "Goku",
    "Gollum",
    "Goofy",
    "Green Lantern",
    "Groot",
    "Hagrid",
    "HAL-9000",
    "Han Solo",
    "Hank Hill",
    "Hannibal Lecter",
    "Harley Quinn",
    "Harry Potter",
    "He-Man",
    "Hellboy",
    "Hello Kitty",
    "Hermione Granger",
    "Homer Simpson",
    "Indiana Jones",
    "Inigo Montoya",
    "Inspector Columbo",
    "Inspector Gadget",
    "Invader Zim",
    "Iron Man",
    "Jabba the Hutt",
    "Jack Skellington",
    "Jafar",
    "James Bond",
    "James T. Kirk",
    "Jar Jar Binks",
    // "Jason Voorhees",
    "Jean-Luc Picard",
    "Jessica Rabbit",
    "Jiminy Cricket",
    "John Shaft",
    "Jonny Quest",
    // "Judge Dredd",
    "Judy Hopps",
    "Jughead",
    "Katniss Everdeen",
    "Kenny",
    "Kermit the Frog",
    "Kim Possible",
    "King Kong",
    "Kirby",
    "Kratos",
    "Kronk",
    "Krusty the Clown",
    "Krypto the Superdog",
    "Lando Calrissian",
    "Lara Croft",
    "Lassie",
    "Legolas",
    "Leslie Knope",
    "Lex Luthor",
    "Lightning McQueen",
    "Link",
    "Lisa Simpson",
    "Lois Lane",
    "Loki",
    "Lola Bunny",
    "Lord Voldemort",
    "Luigi",
    "Luke Skywalker",
    "Luna Lovegood",
    "Lurch",
    "Lydia Deetz",
    "MacGyver",
    "Magneto",
    "Maleficient",
    "Mario",
    "Marion Ravenwood",
    "Mary Poppins",
    "Master Chief",
    "McGruff the Crime Dog",
    "Megamind",
    "Megatron",
    "Meowth",
    "Merlin",
    "Michael Corleone",
    "Mickey Mouse",
    "Minerva McGonagall",
    "Mini-me",
    "Mirror Universe Spock",
    "Miss Piggy",
    "Mothman",
    "Mr. Bean",
    "Mr. Burns",
    "Mr. Fantastic",
    "Mr. Freeze",
    "Mr. Krabs",
    "Mr. Mxyzptlk",
    "Mr. Snuffleupagus",
    "Mr. Toad",
    "Mr. Tumnus",
    "Mrs. Potts",
    "Ms. Frizzle",
    "Mulan",
    "Mystique",
    "Ned Flanders",
    "Neville Longbottom",
    "Nick Fury",
    "Nosferatu",
    "Obi-Wan Kenobi",
    "Olive Oyl",
    "Oogie Boogie",
    "Optimus Prime",
    "Oscar the Grouch",
    "Pac-Man",
    "Paddington Bear",
    "Papa Smurf",
    "Patrick Star",
    "Pennywise the Clown",
    "Pepé Le Pew",
    "Peppa Pig",
    "Perry the Platypus",
    "Peter Griffin",
    "Peter Pan",
    "Piglet",
    "Pikachu",
    "Pinhead",
    "Plankton",
    "Poison Ivy",
    "Popeye",
    "Porky Pig",
    "Princess Bubblegum",
    "Princess Leia",
    "Princess Peach",
    "Professor Moriarty",
    "Puss-in-Boots",
    "Pyramid Head",
    "Q",
    "R2-D2",
    "Rambo",
    "Rapunzel",
    "Red Skull",
    "Richie Rich",
    "Robin the Boy Wonder",
    "Robocop",
    "Rocket Raccoon",
    "Rocky Balboa",
    "Roger Rabbit",
    "Ron Weasley",
    "Ronald McDonald",
    "Rudolph the Red-Nosed Reindeer",
    "Sabrina the Teenage Witch",
    "Sailor Moon",
    "Samus Aran",
    "Sandy Cheeks",
    "Santa Claus",
    "Saruman the White",
    "Sauron",
    "Scar",
    "Scooby Doo",
    "Scotty",
    "Scrappy Doo",
    "Scrooge McDuck",
    "Severus Snape",
    "Shaggy",
    "She-Hulk",
    "She-Ra",
    "Shelob",
    "Sherlock Holmes",
    "Shrek",
    "Sir Topham Hatt",
    "Skeletor",
    "Slenderman",
    "Slimer",
    "Smaug",
    "Smurfette",
    "Snoopy",
    "Snow White",
    "Solid Snake",
    "Sonic the Hedgehog",
    "Speed Racer",
    "Speedy Gonzales",
    "Spock",
    "Spongebob Squarepants",
    "Squidward Tentacles",
    "Squirrel Girl",
    "Starscream",
    "Lt. Sulu",
    "Supergirl",
    "Superman",
    "Tank Girl",
    "Tarzan",
    "Thanos",
    "The Babadook",
    "The Brave Little Toaster",
    "The Cat in the Hat",
    "The Cowardly Lion",
    "The Creature from the Black Lagoon",
    "The Doctor",
    "The Dread Pirate Roberts",
    "The Dude",
    "The Easter Bunny",
    "The Energizer Bunny",
    "The Flash",
    "The Fonz",
    "The Genie",
    "The Grim Reaper",
    "The Grinch",
    "The Human Torch",
    "The Incredible Hulk",
    "The Invisible Girl",
    "The Iron Giant",
    "The Joker",
    "The Jolly Green Giant",
    "The Kool-Aid Man",
    "The Loch Ness Monster",
    "The Lone Ranger",
    "The Mad Hatter",
    "The Man in the Yellow Hat",
    "The Mummy",
    "The Other Mother",
    "The Penguin",
    "The Phantom of the Opera",
    "The Pillsbury Dough Boy",
    "The Pink Panther",
    "The Predator",
    "The Roadrunner",
    "The Sarlacc",
    "The Scarecrow",
    "The Stay-Puft Marshmallow Man",
    "The Swedish Chef",
    "The Tasmanian Devil",
    "The Terminator",
    "The Tin Man",
    "The Tooth Fairy",
    "The Velveteen Rabbit",
    "The Very Hungry Caterpillar",
    "The Wicked Witch of the West",
    "The Wizard of Oz",
    "Thomas the Tank Engine",
    "Thor",
    "Tigger",
    "Tinker Bell",
    "Tintin",
    "Tiny Tim",
    "Tonto",
    "Toto (too)",
    "Totoro",
    "Treebeard",
    "Tuxedo Mask",
    "Tweety Bird",
    "Twilight Sparkle",
    "Tyrion Lannister",
    "Lt. Uhura",
    "Uncle Fester",
    "Ursula",
    "Vegeta",
    "Velma",
    "Veruca Salt",
    "Violet Beauregarde",
    "Vito Corleone",
    "Vizzini",
    "WALL-E",
    "Waluigi",
    "Wario",
    "Wednesday Addams",
    "Wesley Crusher",
    "Wile E. Coyote",
    "Willy Wonka",
    "Wilson (volleyball)",
    "Winnie-the-Pooh",
    // "Wishbone",
    "Wolverine",
    "Wonder Woman",
    "Woody",
    "Worf",
    "Xena, Warrior Princess",
    "Yoda (non-baby)",
    "Yogi Bear",
    "Yosemite Sam",
    "Yoshi",
    "Yzma",
    "Zaphod Beeblebrox",
    "Zapp Brannigan",
    "Zorro"
];


