import { Constants } from "@croquet/worldcore";

export function Question(n) {
    return Constants.Questions[n];
}

export function QuestionCount() {
    return Constants.Questions.length;
}

Constants.Questions = [
    "Who would win a battle to the death?",
    "Who would win a battle of wits?",
    "Who should be king of the world?",
    "Who takes the longest to get ready in the morning?",
    "Who would you rather be stranded on a desert island with?",
    "Who would you rob a bank with?",
    "Who needs to be in therapy?",
    "Who should be utterly erased from existence?",
    "Who would help you hide a body?",
    "Who would be most useful during a zombie apocalypse?",
    "Who's the worst at their job?",
    "Who has the worst pickup line?",
    "Who would you be most surprised to see working at McDonald's?",
    "Who has the best fashion sense?",
    "Who's the worst tipper?",
    "Who would you trust with your darkest secret?",
    "Who would you ask to help you move?",
    "Who would you send back in time to kill Hitler?",
    "Who would you take a road trip with?",
    "Who's the fairest one of all?",
    "Who would you build an IKEA bookcase with?",
    "Who should rescue little Timmy from the well?",
    "Who would you trust to watch the baby?",
    "Who would make the best cult leader?",
    "Who is secretly a sleeper agent?",
    "Who would you spend a weekend in Vegas with?",
    "Who would make the worst middle-school gym teacher?",
    "Who would win a freestyle rap battle?",
    "Who knows how to hold a grudge?",
    'Who would you rather sleep with?',
    "Who would win a talent show?",
    "Who should drive the getaway car?",
    "Who would you avoid if you ran into them at Walmart?",
    "Who would you crash a wedding with?",
    "Who needs a vacation?",
    "Who looks best in drag?",
    "Who had the longest emo phase?",
    "Who picks up the check?",
    "Who's missing the big picture?",
    "Who would you not get into a hot tub with?",
    "Who smells the best?",
    "Who smells the worst?",
    "Who would be the easiest to frame for murder?",
    "Who ate the last cookie?",
    "Who deserves to be taken down a notch?",
    "Who needs hug?",
    "Who looks best in a swimsuit?",
    "Who would you go dumpster diving with?",
    "Who would be first to be voted off the island?",
    "Who would make the worst ex?",
    "Who would ghost you?",
    "Who parties the hardest?",
    "Who can't hold their liquor?",
    "Who's the most diligent about recycling?",
    "Who wants to speak to the manager?",
    "Who's the brains of the operation?",
    "Who's the worst boss?",
    "Who's the best boss?",
    "Who's the cat who won't cop out when there's danger all about?",
    "Who secretly suffers from massive self-loathing?",
    "Who had the worst childhood?",
    "Who would you go to Disneyland with?",
    "Who would you rather have a romantic dinner with?",
    "Who's the absolute worst?",
    "Who really needs a makeover?",
    "Who do you want to switch places with for a day?",
    "Who's the best kisser?",
    "Who's the worst kisser?",
    "Who would you trust to disarm a ticking time bomb?",
    "Who is a ticking time bomb?",
    "Who has the best secret lair?",
    "Who would you trust to clean the bathroom?",
    "Who should star in their own rom-com?",
    "Who would you be least surprised to discover was a serial killer?",
    "Who has the best hair?",
    "Who would be the worst roommate?",
    "Who would be the best roommate?",
    "Who always gets picked last for dodgeball?",
    "Who should be homecoming queen?",
    "Who has the sickest moves?",
    "Who's the most metal?",
    "Who's the most punk?",
    "Who's just phoning it in?",
    "Who throws the best parties?",
    "Who would you like to see host the Oscars?",
    "Who should have their own late night talk show?",
    "Who would you go to for relationship advice?",
    "Who's the biggest gossip?",
    "Who's the biggest dumpster fire?",
    "Who would you not want to owe money to?",
    "Who is trying too hard?",
    "Who would you trust to watch your stuff while you're in the bathroom?",
    "Who would you ask for directions?",
    "Who would you not want to sit next to on an airplane?"
];
