import { Constants } from "@croquet/croquet";

export function Nickname() {
    const a = Math.floor(Math.random() * adjectives.length);
    const n = Math.floor(Math.random() * nouns.length);
    return adjectives[a] + " " + nouns[n];
}

const adjectives = [
    "#1",
    "0g Trans-fat",
    "100% Organic",
    "30-Watt",
    "Admiral",
    "Aggro",
    "Alpha",
    "Amphibious",
    "Angry",
    "Anime",
    "Annoying",
    "Anxious",
    "Assistant",
    "Baby",
    "Barbecued",
    "Battle",
    "Beatboxing",
    "Big Ol'",
    "Blue-collar",
    "Boiled",
    "Brain-dead",
    "Brainy",
    "Broken",
    "Bulletproof",
    "Canned",
    "Cardboard",
    "Cast-iron",
    "Champagne",
    "Cheap Plastic",
    "Chicken-fried",
    "Clockwork",
    "Colonel",
    "Commodore",
    "Conan the",
    "Cool Ranch",
    "Chocolate",
    "Chunk-style",
    "Crazy",
    "Cromulent",
    "Crypto",
    "Curious",
    "Cute Lil'",
    "Cyber",
    "Daddy's Little",
    "Dancing",
    "Dead",
    "Deadly",
    "Defective",
    "Detective",
    "Disco",
    "D.J.",
    "Doomed",
    "Double",
    "Dr.",
    "Dreamy",
    "Dropkick",
    "Drunken",
    "Duck Duck",
    "Eccentric",
    "Eldrich",
    "Electric",
    "Emo",
    "Extreme",
    "Fancy",
    "Fearless",
    "Feral",
    "Flying",
    "Frankenstein's",
    "Freaky",
    "Free-range",
    "Frisky",
    "Fullmetal",
    "Funky",
    "Giant",
    "Glitch",
    "Glowing",
    "Gluten-free",
    "Golden",
    "Goth",
    "Gummi",
    "Hallucinating",
    "Hardboiled",
    "Hardcore",
    "Heavy Metal",
    "Heroic",
    "High-fiber",
    "Hip-hop",
    "Holy",
    "Hungry Hungry",
    "Immature",
    "Immortal",
    "Inch-high",
    "Inconsequential",
    "Infamous",
    "Invisible",
    "Ironic",
    "Kafkaesque",
    "Killer",
    "Kung Fu",
    "Kung Pao",
    "Lengendary",
    "Liquid",
    "Little Miss",
    "Lord",
    "Lovecraftian",
    "Luminous",
    "Lumpy",
    "Luxury",
    "Magical",
    "Malfunctioning",
    "Manic Pixie",
    "Massive",
    "Mayor",
    "M.C.",
    "Mega",
    "Microscopic",
    "Microwave-safe",
    "Mile-high",
    "Miniature",
    "Mirror-universe",
    "Misfit",
    "Mistress",
    "Moist",
    "Monster",
    "Murder",
    "Nacho Cheese",
    "Narcoleptic",
    "Nefarious",
    "Norwegian",
    "Notorious",
    "Nuclear",
    "Obsolete",
    "Part-time",
    "Pernicious",
    "Petrified",
    "Pink",
    "Posh",
    "President",
    "Princess",
    "Professor",
    "Prototype",
    "Public Domain",
    "Quantum",
    "Radioactive",
    "Rainbow",
    "Recently Divorced",
    "Replacement",
    "Rocky Horror",
    "Royal",
    "Rubber",
    "Rubenesque",
    "Sarcastic",
    "Salty",
    "Scary",
    "Sergeant",
    "Second",
    "Secret",
    "Selfless",
    "Sexy",
    "Shameless",
    "Shy",
    "Sly",
    "Smooooth",
    "Sneaky",
    "Sparkle",
    "Spherical",
    "Spicy",
    "Spooky",
    "Stealth",
    "Steamed",
    "Steampunk",
    "Stereotypical",
    "Sticky",
    "Stir-fried",
    "Strange",
    "Subtle",
    "Super",
    "Sweet & Sour",
    "Swol",
    "The Best",
    "The Big Bad",
    "The Eternal",
    "The Fellowship of the",
    "The Last",
    "Thicc",
    "Thrift-store",
    "Timid",
    "Tiny",
    "Total",
    "Transcendental",
    "Trash",
    "Tricky",
    "Troublesome",
    "Ultra",
    "Unauthorized",
    "Uncanny",
    "Undead",
    "Unexpected",
    "Utterly Unremarkable",
    "Vampire",
    "Velveteen",
    "Vengeful",
    "Virtual",
    "Waterproof",
    "Weird",
    "Wonder",
    "Zero Emission",
];

const nouns = [
    "Amoeba",
    "Ant",
    "Antagonist",
    "Apple",
    "Apricot",
    "Astronaut",
    "Baboon",
    "Backhoe",
    "Bacon",
    "Banana",
    "Bean",
    "Bee",
    "Beef",
    "Blizzard",
    "Booty",
    "Brain",
    "Breadstick",
    "Breakfast",
    "Brick",
    "Buckaroo",
    "Bulldozer",
    "Bunny",
    "Burrito",
    "Butterfly",
    "Cactus",
    "Carrot",
    "Caveman",
    "Cheesesteak",
    "Chicken",
    "Chicken Nugget",
    "Cow",
    "Cowboy",
    "Cowgirl",
    "Cucumber",
    "Cupcake",
    "Dad",
    "Dingo",
    "Dirtbag",
    "Dragon",
    "Dreamboat",
    "Dreamgirl",
    "Duck",
    "Dumpster Fire",
    "Dumptruck",
    "Dust Bunny",
    "Dynamite",
    "Egg",
    "Elf",
    "Fairy",
    "Forklift",
    "Freak",
    "Frog",
    "Glitter",
    "Goat",
    "God",
    "Goo",
    "Goldfish",
    "Goose",
    "Gorilla",
    "Gravy",
    "Ham",
    "Hamster",
    "Hedgehog",
    "Hermit",
    "Hero",
    "Hippo",
    "Hobbit",
    "Hobo",
    "Hog",
    "Horse",
    "Hot Pocket",
    "Hovercraft",
    "Hurricane",
    "Jackhammer",
    "Jelly",
    "Kaiju",
    "Kangaroo",
    "Kitty",
    "Lemon",
    "Librarian",
    "Love Interest",
    "Lumberjack",
    "Manatee",
    "Mastermind",
    "McGee",
    "Meatloaf",
    "Megalodon",
    "Mermaid",
    "Messiah",
    "Mom",
    "Monkey",
    "Moose",
    "Mouse",
    "Muffin",
    "Mummy",
    "Mushroom",
    "Narwhal",
    "Necromancer",
    "Ninja",
    "Noodle",
    "Ooze",
    "Orange",
    "Oyster",
    "Panda",
    "Pile Driver",
    "Peanut",
    "Penguin",
    "Pickle",
    "Pigeon",
    "Pirate",
    "Pixie",
    "Pizza",
    "Platypus",
    "Plushie",
    "Pony",
    "Poodle",
    "Potato",
    "Princess",
    "Protagonist",
    "Pudding",
    "Puppy",
    "Riot",
    "Robot",
    "Rock",
    "Rocket",
    "Rodeo",
    "Roomba",
    "Samurai",
    "Sauce",
    "Skeleton",
    "Slime",
    "Shark",
    "Sheep",
    "Snowflake",
    "Soup",
    "Spam",
    "Sperm Whale",
    "Sponge",
    "Spud",
    "Squid",
    "Squirrel",
    "Steamroller",
    "Stick",
    "Sunshine",
    "Supernova",
    "Sushi",
    "T-Rex",
    "Toaster",
    "Tofu",
    "Tofu",
    "Tomato",
    "Tornado",
    "Tractor",
    "Turtle",
    "Underpants",
    "Unicorn",
    "Waif",
    "Wasabi",
    "Weirdo",
    "Witch",
    "Wizard",
    "Wombat",
    "Yak",
    "Zebra",
    "Zeppelin",
    "Zombie",
];
